name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "${{ matrix.version }}"

      - name: Install Dependencies
        run: |
          pip3 install -e ".[dev]"

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Run Pytest
        run: pytest
